name: Manual Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
      draft:
        description: 'Whether to create the release as a draft'
        required: false
        default: false
      prerelease:
        description: 'Whether to mark the release as a prerelease'
        required: false
        default: false

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SonarCloud
      if: github.event_name == 'release'
      uses: sonarsource/sonarcloud-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build
      run: |
        # Add your build commands here

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: ${{ github.event.inputs.version }}
        draft: ${{ github.event.inputs.draft }}
        prerelease: ${{ github.event.inputs.prerelease }}

    - name: Publish on Maven
      run: |
        # Add commands to publish on Maven repository

    - name: Publish on Forge
      run: |
        # Add commands to publish on Forge repository

    - name: Publish on Modrinth
      run: |
        # Add commands to publish on Modrinth repository
