name: Manual Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
      draft:
        description: 'Whether to create the release as a draft'
        required: false
        default: false
      prerelease:
        description: 'Whether to mark the release as a prerelease'
        required: false
        default: false

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu' # Alternative distribution options are available

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Set permission
      run: chmod +x ./gradlew

    - name: Use Gradle 8.3
      run: ./gradlew wrapper --gradle-version 8.3

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./gradlew build
        ./gradlew sonar --stacktrace

    - name: Publish on GitHub Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: v${{ github.event.inputs.version }}
        title: "Automated Build ${{ github.event.inputs.version }}"
        prerelease: true
        files: fabric/build/libs/$(grep -oP '(?<=mod_id_kebabs = \')[^\']+' build.gradle)-fabric-$(grep -oP '(?<=minecraft_version = \')[^\']+' build.gradle).jar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: fabric/build/libs/$(grep -oP '(?<=mod_id_kebabs = \')[^\']+' build.gradle)-fabric-$(grep -oP '(?<=minecraft_version = \')[^\']+' build.gradle).jar
        retention-days: 1


    - name: Publish on Maven
      run: |
        # Add commands to publish on Maven repository

    - name: Publish on Forge
      run: |
        # Add commands to publish on Forge repository

    - name: Publish on Modrinth
      run: |
        # Add commands to publish on Modrinth repository
