name: Manual Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
      draft:
        description: 'Whether to create the release as a draft'
        required: false
        default: false
      prerelease:
        description: 'Whether to mark the release as a prerelease'
        required: false
        default: false

jobs:

 
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu' # Alternative distribution options are available

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Set permission
      run: chmod +x ./gradlew

    - name: Use Gradle 8.3
      run: ./gradlew wrapper --gradle-version 8.3

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to create releases
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Needed for Sonar analysis, if any
      run: |
        ./gradlew build
        ./gradlew sonar --stacktrace

    #- uses: BrycensRanch/read-properties-action@v1.0.3
    #  id: all
    #  with:
    #   file: gradle.properties
    #    all: true

   # - run: echo ${{ steps.all.outputs.mod_version  }} # Project's version from gradle.properties

    - name: Publish 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        CURSEFORGE: ${{ secrets.CURSEFORGE }}
        MODRINTH: ${{ secrets.MODRINTH }}
      run: |
        ./gradlew publish --stacktrace
     
